name: Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      image-version:
        description: 'Docker image version'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - name: set lower case owner name
          run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'
        - uses: actions/checkout@v2
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build the hello-docker Docker image
          run: |
             docker build . --tag ghcr.io/${{ OWNER_LC }}/${{ inputs.image-name }}:${{ inputs.image-version }} .
             docker run ghcr.io/${{ OWNER_LC }}/${{ inputs.image-name }}:${{ inputs.image-version }} .
             docker push ghcr.io/${{ OWNER_LC }}/${{ inputs.image-name }}:${{ inputs.image-version }} .
