name: Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      image-version:
        description: 'Docker image version'
        required: true
        type: string
      custom-dockerfile:
          description: 'If you want to use a custom Dockerfile, the path to the image Dockerfile'
          required: false
          type: string
          default: '.'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - name: set lower case owner name
          run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'
        - uses: actions/checkout@v2
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image    
          uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
          with:
            context: ${{ inputs.custom-dockerfile }}
            push: ${{ github.event_name != 'pull_request' }}
            tags: ghcr.io/${{ env.OWNER_LC }}/${{ inputs.image-name }}:${{ inputs.image-version }} 
